# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7b56d56dfbe2f683b545274fd67df37b4d68acbc1bd698f608e6d1c83b0e191cb560f6f020db50c5876fa2eb02510487587eedbbdeb18549c52afe9ae7aaf12

test:
  secret_key_base: b682e0bc6721b2e38acfc9c0b7da30621013761018882fb8a2655345ca58475bf0e3fbf18907a2e79a82adc1edeedc76a295f34795979aeaf3bfae1b85ee8bb4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
